<?php get_header();?>
<form action="/bitcoin" method="POST">
    <label for="btc_amount">BitCoin Amount:</label>
    <input type="number" value="1" name="btc_amount" id="btc_amount"  step="0.1" />
    <input type="submit" value="Convert to &pound;GBP" />
</form>
<?php if(WordCampMcr_ExternalApi::isSubmitted()):
    $results = WordCampMcr_ExternalApi::getResults();
?>
<hr />
<h1> Results</h1>
<h2><?php echo $results['btc_amount'], ' BTC is worth &pound;', number_format($results['currency_amount'],2); ?></h2>
    <?php endif; ?>
<?php get_footer(); ?>